name = "compliance-admin-pages"
account_id = "2a49cc296188fe3b7e3c33e98f1d4cd2"
compatibility_date = "2026-02-15"
pages_build_output_dir = "dist"

[vars]
ENV_NAME = "dev"
API_BASE_URL = "https://compliance-api.natescloud.workers.dev"

[env.staging.vars]
ENV_NAME = "staging"
API_BASE_URL = "https://staging-compliance-api.example.com"

[env.prod.vars]
ENV_NAME = "prod"
API_BASE_URL = "https://api.example.com"
